### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by i-am-annewang** [i-am-annewang/wanghuiying.github.io#37]
valuse = [“CL1”], return fieldName = “ネックレス”
what if values = [“CL1”, “CL2"], should return  fieldName = “ネックレス,  ネッス“?

- [ ] Consider to get whole values from field Collection instead of get first item of values?
- [ ] figure how to get japanse collection name from code 'CL1'
```js
// getProductField returns the raw field value inside the `product.filterProperties`.
const getProductField = (
  fieldName: ProductField,
  product: products.IProduct
): string | null => {
  if (!product.filterProperties) {
    return null;
  }

  const property = product.filterProperties.find(
    ({ field }) => field === fieldName
  );

  if (!property || !property.values || property.values.length === 0) {
    return null;
  }

  return property.values[0]; // ? should return property.values
};
```
```js
productResponse{
   code: 'ES-00',
   properties: [
    { 
      "field": "Collection",
      "inValues": ["CL1"]
    }
   ]
}

const rdGroups = [
  {
    info: {
      itemType: "ProductFilterProperties",
      code: ProductField.Collection
    },
    items: [
      {
        itemType: ProductField.Collection,
        code: "CL1",
        slug: "necklace",
        name: "ネックレス"
      }
    ]
  }
];
```
---
- [x] [高效使用mac](http://xialeizhou.com/2019/06/23/%E9%AB%98%E6%95%88macbook%E5%B7%A5%E4%BD%9C%E7%8E%AF%E5%A2%83%E9%85%8D%E7%BD%AE/#more)
- [ ] [1password](https://sspai.com/post/35195)
- [x] [mac简单入门](https://sspai.com/post/41371)
- [x] [mac的快捷键](https://support.apple.com/zh-cn/HT201236)
- [ ] 鸟哥的私房菜
- [ ] Linux command
- [ ] Vim
- [ ] alfred + workflow  
  + `find filename` -- find file path
  + `open filename`  -open file
  + 加入书签栏
- [x] git cherry-pick commit号
- [x] vscode 快捷键
- [ ] git soft 如何使用
- [x] 修复`code .`不能打开当前目录的问题，写的脚本不对
- [ ] 把图片放到docker里面，然后写在代码注释里
- [x] 录制gif图

+ read commits of https://github.com/theplant/mastani/pull/235/commits/0e62784f87d1d9fdcb72d2c89cbb578f85ef1257
+ http://markyun.github.io/2016/Pseudo-class-Pseudo-Element/
```
:Pseudo-classes     伪类:DOM在不同状态、不同位置下的特殊效果；
::Pseudo-elements   伪元素：DOM按匹配规则伪造出的元素；
```
常用伪元素
```
::after         在元素的内容之后
::before        在元素的内容之前
::first-line    元素的第一行
::first-letter  元素的第一个字母
::placeholder   占位符，用于input输入框之类的提醒
::selection     被选取的元素，用于改变网页被选中部分的效果

:active         当元素被点击的时
:blank          空白的元素
:checked        被选中的元素
:default        默认被选中或默认会被提交的元素
:dir()          匹配特定文字书写方向的元素
:disabled       处于被禁止操作状态的元素
:empty          没有任何内容的元素
:enabled        处于可操作状态的元素
:first          用于打印文档的第一页
:first-child    父级元素下的第一个子元素
:first-of-type  父级元素下的第一个同类子元素
:focus          当元素成为焦点
:fullscreen     当元素被HTML5 API调用RequestFullscreen方式全屏时
:hover          当鼠标移动到链接元素上面时
:in-range       当元素属性值处于其指定的范围内时    
:indeterminate  当元素属性值处于不确定状态的
:invalid        当元素属性值不是指定的type属性时
:lang()         匹配有正确lang 属性值的元素，如 lang(zh-Hans)
:last-child     元素的最后一个子元素
:last-of-type   元素的最后一个同类子元素
:left           选择打印文档的左侧页
:link           未被访问的链接元素
:not()          否定选择器（不匹配条件则生效）
:nth-child()    元素的一个或多个特定的子元素
:nth-last-child() 元素的一个或多个特定的子元素，从该元素的最后一个子元素开始算；
:nth-of-type()  选择指定的元素
:nth-last-of-type() 选择指定的元素，从元素的最后一个开始计算
:only-child     元素是它的父元素的唯一子元素
:only-of-type   元素是它的父级元素的唯一一个相同类型的子元素
:optional       未指定required属性的表单元素
:out-of-range   超出规定值范围的元素
:read-only      元素设置了 'readonly' 属性生效
:read-write     元素没有 "readonly" 属性生效
:required       设置了 "required" 属性的元素    
:right          选择打印文档的左侧页
:root           文档的根元素
:scope          作用域的伪类，默认为HTML（案例 :scope #mammma {...}）
:target         当前活动的元素（匹配页面URI中对应的目标元素）
:valid          表示有效的元素
:visited        已被访问过的元素
 content        在元素之前或之后添加的内容。
```

+ graphql 模式（schema）、查询（query）、解析器（resolver）

+ 超级小的svg icon, 每个都基本小于1k https://github.com/edent/SuperTinyIcons
![image](https://user-images.githubusercontent.com/18532655/33476585-7158bac6-d6bd-11e7-8cc6-79dde2383004.png)

+ 阅读PWA中文书📖 https://github.com/SangKa/PWA-Book-CN

**Comment by WangHuiying** [comment]
Typescripts
添加typescript配置文件
https://github.com/vilic/TypeScript-1/blob/master/doc/handbook/quick-start/knockout.md

**Comment by WangHuiying** [comment]
删除一个本地分支
git branch 分支号
删除一个远程分支
git push origin :远程分支号

**Comment by WangHuiying** [comment]
一般的line-height是行高，默认是垂直居中的
注意两个扩大版的点击区域不应该出现重叠的部分

**Comment by WangHuiying** [comment]
https://github.com/leecade/react-native-swiper

**Comment by WangHuiying** [comment]
利用Xcode安装ios模拟器
http://www.pc6.com/edu/82278.html

**Comment by WangHuiying** [comment]
command  + <= 删除文件delete
command + z - 撤销undo
command + shift + z 重做redo

**Comment by WangHuiying** [comment]
https://benfrain.com/a-horizontal-scrolling-navigation-pattern-for-touch-and-mouse-with-moving-current-indicator/

**Comment by WangHuiying** [comment]
动态设置和调用 styled-components 样式
http://www.59m59s.com/blog/dong-tai-she-zhi-he-diao-yong-styled-componentsyang-shi/
react又是使用javascript来控制html和css
http://www.ruanyifeng.com/blog/2017/04/css_in_js.html
styled-components 在响应式设计中的表现
http://www.59m59s.com/blog/styled-componentszai-xiang-ying-shi-she-ji-zhong-de-biao-xian/

**Comment by WangHuiying** [comment]
safari的开发者模式
![image](https://user-images.githubusercontent.com/18532655/32873094-3c9e2996-cac5-11e7-91f5-f49e5ddb47d1.png)
![image](https://user-images.githubusercontent.com/18532655/32873097-3e6e479c-cac5-11e7-8fb2-641ec4272c42.png)

**Comment by WangHuiying** [comment]
http://zh-tw.learnlayout.com/

![image](https://user-images.githubusercontent.com/18532655/32927922-4b5b132a-cb8a-11e7-958c-3088242f3cad.png)

**Comment by WangHuiying** [comment]
![image](https://user-images.githubusercontent.com/18532655/33115682-cef61250-cf9c-11e7-9d71-5efac901ed4b.png)

https://www.npmjs.com/package/scroll-into-view-if-needed

https://stipsan.github.io/scroll-into-view-if-needed/

https://github.com/stipsan/scroll-into-view-if-needed#react

```
import scrollIntoViewIfNeeded from "scroll-into-view-if-needed";
selectImage(selected: number) {
    this.setState({ selected });
    let node = findDOMNode(this.thumbRefs[selected]);
    scrollIntoViewIfNeeded(node, {
      centerIfNeeded: true
    });
}
```
but test it, and it only works in webkit, e.g. chrome and safari

**Comment by WangHuiying** [comment]
Cause I cannot solve this 1px bug, I use `scroll-into-view-if-needed` instead.
![image](https://user-images.githubusercontent.com/18532655/33115682-cef61250-cf9c-11e7-9d71-5efac901ed4b.png)

https://www.npmjs.com/package/scroll-into-view-if-needed

https://stipsan.github.io/scroll-into-view-if-needed/

https://github.com/stipsan/scroll-into-view-if-needed#react

```
import scrollIntoViewIfNeeded from "scroll-into-view-if-needed";
selectImage(selected: number) {
    this.setState({ selected });
    let node = findDOMNode(this.thumbRefs[selected]);
    scrollIntoViewIfNeeded(node, {
      centerIfNeeded: true
    });
}
```
but test it, and it only works in webkit, e.g. chrome and safari

**Comment by WangHuiying** [comment]
A union type describes a value that can be one of several types. We use the vertical bar `(|)` to separate each type, so `number | string | boolean` is the type of a value that can be a `number`, a `string`, or a `boolean`.

**Comment by WangHuiying** [comment]
o magic is involved, it auto-creates Redux store when `getInitialProps` is called by `Next.js` and then passes this store down to React Redux's `Provider`, which is used to wrap the original component, also automatically. On the client side it also takes care of using same store every time, whereas on server new store is created for each request.

```jsx
import withRedux from "next-redux-wrapper";
return withRedux(makeStore)(Page);
```

**Comment by WangHuiying** [comment]
https://github.com/modosc/react-responsive-redux
```jsx
import { setMobileDetect, mobileParser } from "react-responsive-redux";

params.store.dispatch(setMobileDetect(mobileParser(params.req)));
```

**Comment by WangHuiying** [comment]
Promise

```
function successCallback(result) {
  console.log("It succeeded with " + result);
}

function failureCallback(error) {
  console.log("It failed with " + error);
}

doSomething(successCallback, failureCallback);
```
```
let promise = doSomething(); 
promise.then(successCallback, failureCallback);
```
```
doSomething().then(successCallback, failureCallback);
```
![image](https://user-images.githubusercontent.com/18532655/33164431-bcb52b36-d06d-11e7-9997-c7a963652822.png)

**Comment by WangHuiying** [comment]
![image](https://user-images.githubusercontent.com/18532655/33164777-410883fa-d06f-11e7-89a6-b1b0225dba9c.png)

**Comment by WangHuiying** [comment]
typescript给类型取别名, 类型别名常用于联合类型
```jsx
type Name = string;
type NameResolver = () => string;
type NameOrResolver = Name | NameResolver;
```

https://ts.xcatliu.com/advanced/string-literal-types.html
字符串字面量类型
```jsx
type EventNames = 'click' | 'scroll' | 'mousemove';
function handleEvent(ele: Element, event: EventNames) {
  // do something
}

handleEvent(document.getElementById('hello'), 'scroll');  // 没问题
handleEvent(document.getElementById('world'), 'dbclick'); // 报错，event 不能为 'dbclick'

// index.ts(7,47): error TS2345: Argument of type '"dbclick"' is not assignable to parameter of type 'EventNames'.
```

类型别名与字符串字面量类型都是使用 type 进行定义

**Comment by WangHuiying** [comment]
模板字符串
其中 \`用来定义 ES6 中的模板字符串，`${expr} `用来在模板字符串中嵌入表达式
```jsx
let sentence: string = `Hello, my name is ${myName}.
I'll be ${myAge + 1} years old next month.`;
```

**Comment by WangHuiying** [comment]
任意值（Any）用来表示允许赋值为任意类型。
在任意值上访问任何属性都是允许的
也允许调用任何方法

**Comment by WangHuiying** [comment]
联合类型
联合类型（Union Types）表示取值可以为多种类型中的一种。
联合类型使用 `|` 分隔每个类型。
```jsx
let myFavoriteNumber: string | number;
```
当 TypeScript 不确定一个联合类型的变量到底是哪个类型的时候，我们只能访问此联合类型的所有类型里共有的属性或方法

**Comment by WangHuiying** [comment]
对象的类型——接口`interfaces`
是对行为的抽象，而具体如何行动需要由类（`classes`）去实现（`implements`)。
接口一般首字母大写
赋值的时候，变量的形状必须和接口的形状保持一致
```jsx
interface Person {
    name: string;
    age: number;
}

let tom: Person = {
    name: 'Tom',
    age: 25
};
```
可选属性`?`
```jsx
interface Person {
    name: string;
    age?: number;
}

let tom: Person = {
    name: 'Tom'
};
```
任意属性`any`
```jsx
interface Person {
    name: string;
    age?: number;
    [propName: string]: any;
}
```
只读属性`readonly`
注意，只读的约束存在于第一次给对象赋值的时候，而不是第一次给只读属性赋值的时候
```jsx
interface Person {
    readonly id: number;
    name: string;
    age?: number;
    [propName: string]: any;
}
```

**Comment by WangHuiying** [comment]
数组的类型
「类型 + 方括号」表示法
```jsx
let fibonacci: number[] = [1, 1, 2, 3, 5];
```
数组泛型`Array Generic` `Array<elemType>`
```
let fibonacci: Array<number> = [1, 1, 2, 3, 5];
```

**Comment by WangHuiying** [comment]
函数的类型
```
// 函数声明（Function Declaration）
function sum(x, y) {
    return x + y;
}

// 函数表达式（Function Expression）
let mySum = function (x, y) {
    return x + y;
};
```

```jsx
function sum(x: number, y: number): number {
    return x + y;
}
```
在 TypeScript 的类型定义中，`=>` 用来表示函数的定义，左边是`输入类型`，需要用`括号`括起来，右边是`输出类型`。
在 ES6 中，=> 叫做箭头函数
```jsx
let mySum: (x: number, y: number) => number = function (x: number, y: number): number {
    return x + y;
};
```
用接口定义函数的形状
```jsx
interface SearchFunc {
    (source: string, subString: string): boolean;
}

let mySearch: SearchFunc;
mySearch = function(source: string, subString: string) {
    return source.search(subString) !== -1;
}
```
可选参数`?`, 可选参数后面不允许再出现必须参数
```jsx
function buildName(firstName: string, lastName?: string) {
    if (lastName) {
        return firstName + ' ' + lastName;
    } else {
        return firstName;
    }
}
let tom = buildName('Tom');
```
参数默认值, **TypeScript 会将添加了默认值的参数识别为可选参数**, 此时就不受「可选参数必须接在必需参数后面」的限制了
```jsx
function buildName(firstName: string, lastName: string = 'Cat') {
    return firstName + ' ' + lastName;
}
let tomcat = buildName('Tom', 'Cat');
let tom = buildName('Tom');
```
剩余参数, `...rest` 的方式获取函数中的剩余参数, rest 参数只能是最后一个参数
```jsx
function push(array, ...items) {
    items.forEach(function(item) {
        array.push(item);
    });
}
```
reverse 重载函数
```jsx
function reverse(x: number): number;
```

**Comment by WangHuiying** [comment]
类型断言`Type Assertion`
1. <类型>值`<string>something`
2. <类型>值
类型断言不是类型转换，断言成一个联合类型中不存在的类型是不允许的

**Comment by WangHuiying** [comment]
当使用第三方库时，我们需要引用它的声明文件。
我们需要使用 declare 关键字来定义它的类型，帮助 TypeScript 判断我们传入的参数类型对不对：
```jsx
declare var jQuery: (string) => any;
```
通常我们会把类型声明放到一个单独的文件中，这就是声明文件, 约定声明文件以 .d.ts 为后缀：
```jsx
// jQuery.d.ts
declare var jQuery: (string) => any;
```
然后在使用到的文件的开头，用「三斜线指令」表示引用了声明文件：
```
/// <reference path="./jQuery.d.ts" />
```
第三方声明文件 `@types`

**Comment by WangHuiying** [comment]
ECMAScript 的内置对象`Boolean`、`Error`、`Date`、`RegExp`
DOM 和 BOM 的内置对象`Document`、`HTMLElement`、`Event`、`NodeList`
TypeScript 核心库的定义中不包含 Node.js 部分,
Node.js 不是内置对象的一部分，如果想用 TypeScript 写 Node.js，则需要引入第三方声明文件：
```
npm install @types/node --save-dev
```

**Comment by WangHuiying** [comment]
枚举`Enum`, 枚举成员会被赋值为从 0 开始递增的数字，同时也会对枚举值到枚举名进行反向映射
枚举项手动赋值enum Days {Sun = 7, Mon = 1, Tue, Wed, Thu, Fri, Sat};
未手动赋值的枚举项会接着上一个枚举项递增。
手动赋值的枚举项可以不是数字，此时需要使用类型断言来让 tsc 无视类型检查 
```jsx
enum Days {Sun = 7, Mon, Tue, Wed, Thu, Fri, Sat = <any>"S"};
```
枚举项有两种类型：常数项（constant member）和计算所得项（computed member）
计算所得项, 如果紧接在计算所得项后面的是未手动赋值的项，那么它就会因为无法获得初始值而报错
常数枚举`const enum`
```jsx
const enum Directions {
  Up,
  Down,
  Left,
  Right
}
```
编译之后
```jsx
var directions = [0 /* Up */, 1 /* Down */, 2 /* Left */, 3 /* Right */];
```
外部枚举
```jsx
declare enum Directions {
  Up,
  Down,
  Left,
  Right
}

let directions = [Directions.Up, Directions.Down, Directions.Left, Directions.Right];
```

**Comment by WangHuiying** [comment]
类Class https://ts.xcatliu.com/advanced/class.html
使用 class 定义类，使用 constructor 定义构造函数。
通过 new 生成新实例的时候，会自动调用构造函数。
```jsx
class Animal {
  constructor(name) {
    this.name = name;
  }
  sayHi() {
    return `My name is ${this.name}`;
  }
}

let a = new Animal('Jack');
console.log(a.sayHi()); // My name is Jack
```
类的继承
使用 `extends` 关键字实现继承，子类中使用 `super` 关键字来调用父类的构造函数和方法
```jsx
class Cat extends Animal {
  constructor(name) {
    super(name); // 调用父类的 constructor(name)
    console.log(this.name);
  }
  sayHi() {
    return 'Meow, ' + super.sayHi(); // 调用父类的 sayHi()
  }
}

let c = new Cat('Tom'); // Tom
```
存取器-使用 `getter` 和 `setter` 可以改变属性的赋值和读取行为：
```jsx
class Animal {
  constructor(name) {
    this.name = name;
  }
  get name() {
    return 'Jack';
  }
  set name(value) {
    console.log('setter: ' + value);
  }
}
```
静态方法
使用 `static` 修饰符修饰的方法称为静态方法，它们不需要实例化，而是直接通过类来调用：
```jsx
class Animal {
  static isAnimal(a) {
    return a instanceof Animal;
  }
}

Animal.isAnimal(a); 
```
实例属性
静态属性
```jsx
class Animal {
  static num = 42;

  constructor() {
    // ...
  }
}

console.log(Animal.num); // 42
```
TypeScript 可以使用三种访问修饰符（Access Modifiers），分别是 `public`、`private` 和 `protected`。

抽象类`abstract`, 不允许被实例化的

typescript 类
```jsx
class Animal {
  name: string;
  constructor(name: string) {
    this.name = name;
  }
  sayHi(): string {
    return `My name is ${this.name}`;
  }
}

let a: Animal = new Animal('Jack');
console.log(a.sayHi()); // My name is Jac
```

**Comment by WangHuiying** [comment]
一个类可以实现多个接口
```jsx
interface Alarm {
  alert();
}

interface Light {
  lightOn();
  lightOff();
}

class Car implements Alarm, Light {
  alert() {
    console.log('Car alert');
  }
  lightOn() {
    console.log('Car light on');
  }
  lightOff() {
    console.log('Car light off');
  }
}
```
接口与接口之间可以是继承关系：
```jsx
interface Alarm {
  alert();
}

interface LightableAlarm extends Alarm {
  lightOn();
  lightOff();
}
```
接口也可以继承类

**Comment by WangHuiying** [comment]
终于配置成功ipv6
https://github.com/XX-net/XX-Net/wiki/IPv6-Win10

**Comment by WangHuiying** [comment]
这个更加厉害
![image](https://user-images.githubusercontent.com/18532655/33240919-8d849e26-d2f9-11e7-9bb2-77bbe47bcfea.png)

**Comment by WangHuiying** [comment]
https://electronjs.org/docs/tutorial/quick-start
![image](https://user-images.githubusercontent.com/18532655/33354803-8e168942-d4ef-11e7-933f-6a13859ec3c5.png)

**Comment by WangHuiying** [comment]
https://github.com/adamschwartz/magic-of-css

**Comment by WangHuiying** [comment]
重启docker
install codeclimate
```
brew update
brew upgrade codeclimate
```
`codeclimate analyze containers/product/ImagePopup*`

学习linux命令`daemon`守护进程

**Comment by WangHuiying** [comment]
dockfile
```cmd
# Base images 基础镜像
FROM centos

#MAINTAINER 维护者信息
MAINTAINER lorenwe 

#ENV 设置环境变量
ENV PATH /usr/local/nginx/sbin:$PATH

#ADD  文件放在当前目录下，拷过去会自动解压
ADD nginx-1.13.7.tar.gz /tmp/

#RUN 执行以下命令
RUN rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7 \
    && yum update -y \
    && yum install -y vim less wget curl gcc automake autoconf libtool make gcc-c++ zlib zlib-devel openssl openssl-devel perl perl-devel pcre pcre-devel libxslt libxslt-devel \
    && yum clean all \
    && rm -rf /usr/local/src/*
RUN useradd -s /sbin/nologin -M www

#WORKDIR 相当于cd
WORKDIR /tmp/nginx-1.13.7

RUN ./configure --prefix=/usr/local/nginx --user=www --group=www --with-http_ssl_module --with-pcre && make && make install

RUN cd / && rm -rf /tmp/

COPY nginx.conf /usr/local/nginx/conf/

#EXPOSE 映射端口
EXPOSE 80 443

#ENTRYPOINT 运行以下命令
ENTRYPOINT ["nginx"]

#CMD 运行以下命令
CMD ["-h"]

作者：-世界那么脏
链接：https://juejin.im/post/5a1bd8a36fb9a0450f21a966
来源：掘金
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。
```

**Comment by WangHuiying** [comment]
20 个 CSS 高级技巧汇总 http://mp.weixin.qq.com/s/MavtDznPVECblDUTq_W-Rg

**Comment by WangHuiying** [comment]
iterm 开启自动补全 https://xiaozhou.net/learn-the-command-line-iterm-and-zsh-2017-06-23.html

**Comment by WangHuiying** [comment]
配置iterm
https://xiaozhou.net/learn-the-command-line-iterm-and-zsh-2017-06-23.html
可以试试 Preferences -> Profiles -> Text -> Text Rendering 把 Draw bold text in bright colors 前面的勾去掉：

![image](https://user-images.githubusercontent.com/18532655/33369353-370c8684-d52f-11e7-9ed2-2cfbc04e686b.png)
